main: main.cpp COO2CSR.cpp CGSolver.cpp matvecops.cpp COO2CSR.hpp CGSolver.hpp matvecops.hpp
	g++ -std=c++11 -Wall -Wextra -Wconversion main.cpp COO2CSR.cpp CGSolver.cpp matvecops.cpp -o main
.PHONY: clean
clean: 
	$(RM) main
